"""Pluggable graph engine connectors for Memory Growth.

The connector layer consumes the local graph indexes generated by
``graph_sync_adapter``. Markdown Wiki remains the source of truth; connectors
are replaceable sinks for search, temporal reasoning, and external graph
engines.
"""

from __future__ import annotations

import json
import os
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Protocol

from .memory_growth import ensure_memory_growth_scaffold, memory_growth_dir


@dataclass(slots=True)
class GraphConnectorResult:
    connector_id: str
    ok: bool
    node_count: int
    edge_count: int
    status: str
    report_path: Path
    warnings: list[str] = field(default_factory=list)
    details: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "connector_id": self.connector_id,
            "ok": self.ok,
            "node_count": self.node_count,
            "edge_count": self.edge_count,
            "status": self.status,
            "report_path": str(self.report_path),
            "warnings": list(self.warnings),
            "details": self.details,
        }


class GraphEngineConnector(Protocol):
    connector_id: str

    def sync(self, nodes: list[dict[str, Any]], edges: list[dict[str, Any]], *, sync_id: str) -> GraphConnectorResult:
        ...


class LocalJsonGraphConnector:
    connector_id = "local_json_graph"

    def sync(self, nodes: list[dict[str, Any]], edges: list[dict[str, Any]], *, sync_id: str) -> GraphConnectorResult:
        root = memory_growth_dir()
        connector_dir = root / "graph" / "connectors" / self.connector_id
        connector_dir.mkdir(parents=True, exist_ok=True)
        snapshot_path = connector_dir / "latest_snapshot.json"
        snapshot = {
            "schema_version": 1,
            "connector_id": self.connector_id,
            "sync_id": sync_id,
            "created_at": _iso_now(),
            "nodes": nodes,
            "edges": edges,
        }
        snapshot_path.write_text(json.dumps(snapshot, ensure_ascii=False, indent=2, default=str) + "\n", encoding="utf-8")
        return _write_connector_report(
            connector_id=self.connector_id,
            sync_id=sync_id,
            ok=True,
            status="synced",
            nodes=nodes,
            edges=edges,
            details={"snapshot_path": str(snapshot_path)},
        )


class CogneeConnector:
    connector_id = "cognee"

    def sync(self, nodes: list[dict[str, Any]], edges: list[dict[str, Any]], *, sync_id: str) -> GraphConnectorResult:
        endpoint = os.getenv("JACHIN_COGNEE_ENDPOINT", "").strip()
        api_key = os.getenv("JACHIN_COGNEE_API_KEY", "").strip()
        if not endpoint:
            return _write_connector_report(
                connector_id=self.connector_id,
                sync_id=sync_id,
                ok=False,
                status="not_configured",
                nodes=nodes,
                edges=edges,
                warnings=["JACHIN_COGNEE_ENDPOINT is not configured"],
                details={"required_env": ["JACHIN_COGNEE_ENDPOINT"], "optional_env": ["JACHIN_COGNEE_API_KEY"], "api_key_present": bool(api_key)},
            )
        return _write_connector_report(
            connector_id=self.connector_id,
            sync_id=sync_id,
            ok=False,
            status="connector_stub_ready",
            nodes=nodes,
            edges=edges,
            warnings=["Cognee transport is not enabled in this build; local graph event contract is ready."],
            details={"endpoint": endpoint, "api_key_present": bool(api_key)},
        )


class GraphitiConnector:
    connector_id = "graphiti"

    def sync(self, nodes: list[dict[str, Any]], edges: list[dict[str, Any]], *, sync_id: str) -> GraphConnectorResult:
        endpoint = os.getenv("JACHIN_GRAPHITI_ENDPOINT", "").strip()
        api_key = os.getenv("JACHIN_GRAPHITI_API_KEY", "").strip()
        if not endpoint:
            return _write_connector_report(
                connector_id=self.connector_id,
                sync_id=sync_id,
                ok=False,
                status="not_configured",
                nodes=nodes,
                edges=edges,
                warnings=["JACHIN_GRAPHITI_ENDPOINT is not configured"],
                details={"required_env": ["JACHIN_GRAPHITI_ENDPOINT"], "optional_env": ["JACHIN_GRAPHITI_API_KEY"], "api_key_present": bool(api_key)},
            )
        return _write_connector_report(
            connector_id=self.connector_id,
            sync_id=sync_id,
            ok=False,
            status="connector_stub_ready",
            nodes=nodes,
            edges=edges,
            warnings=["Graphiti transport is not enabled in this build; temporal event contract is ready."],
            details={"endpoint": endpoint, "api_key_present": bool(api_key)},
        )


def sync_graph_engine_connectors(connector_ids: list[str] | None = None) -> list[GraphConnectorResult]:
    """Run selected graph connectors against the latest local graph indexes."""

    ensure_memory_growth_scaffold()
    nodes, edges, sync_id = _load_latest_graph()
    connectors = _selected_connectors(connector_ids)
    results = [connector.sync(nodes, edges, sync_id=sync_id) for connector in connectors]
    _write_connector_index(results)
    return results


def _selected_connectors(connector_ids: list[str] | None) -> list[GraphEngineConnector]:
    registry: dict[str, GraphEngineConnector] = {
        LocalJsonGraphConnector.connector_id: LocalJsonGraphConnector(),
        CogneeConnector.connector_id: CogneeConnector(),
        GraphitiConnector.connector_id: GraphitiConnector(),
    }
    ids = connector_ids or [LocalJsonGraphConnector.connector_id]
    out: list[GraphEngineConnector] = []
    for connector_id in ids:
        connector = registry.get(str(connector_id).strip())
        if connector:
            out.append(connector)
    if not out:
        out.append(registry[LocalJsonGraphConnector.connector_id])
    return out


def _load_latest_graph() -> tuple[list[dict[str, Any]], list[dict[str, Any]], str]:
    root = memory_growth_dir()
    node_path = root / "indexes" / "graph_nodes.json"
    edge_path = root / "indexes" / "graph_edges.json"
    if not node_path.exists() or not edge_path.exists():
        from .graph_sync_adapter import sync_memory_growth_graph

        sync_memory_growth_graph()
    node_payload = _read_json(node_path)
    edge_payload = _read_json(edge_path)
    sync_id = str(node_payload.get("sync_id") or edge_payload.get("sync_id") or f"graph_connector_{uuid.uuid4().hex[:8]}")
    return list(node_payload.get("nodes") or []), list(edge_payload.get("edges") or []), sync_id


def _write_connector_report(
    *,
    connector_id: str,
    sync_id: str,
    ok: bool,
    status: str,
    nodes: list[dict[str, Any]],
    edges: list[dict[str, Any]],
    warnings: list[str] | None = None,
    details: dict[str, Any] | None = None,
) -> GraphConnectorResult:
    root = memory_growth_dir()
    reports_dir = root / "graph" / "connector_reports" / connector_id
    reports_dir.mkdir(parents=True, exist_ok=True)
    report_path = reports_dir / f"{time.strftime('%Y%m%d_%H%M%S')}_{uuid.uuid4().hex[:8]}.json"
    payload = {
        "schema_version": 1,
        "connector_id": connector_id,
        "sync_id": sync_id,
        "ok": ok,
        "status": status,
        "node_count": len(nodes),
        "edge_count": len(edges),
        "warnings": list(warnings or []),
        "details": details or {},
        "created_at": _iso_now(),
    }
    report_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, default=str) + "\n", encoding="utf-8")
    return GraphConnectorResult(
        connector_id=connector_id,
        ok=ok,
        node_count=len(nodes),
        edge_count=len(edges),
        status=status,
        report_path=report_path,
        warnings=list(warnings or []),
        details=details or {},
    )


def _write_connector_index(results: list[GraphConnectorResult]) -> None:
    root = memory_growth_dir()
    path = root / "indexes" / "graph_connectors.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "updated_at": _iso_now(),
                "connectors": [result.to_dict() for result in results],
            },
            ensure_ascii=False,
            indent=2,
            default=str,
        )
        + "\n",
        encoding="utf-8",
    )


def _read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _iso_now() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%S%z")
