# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from core.transport import jachin_link_pb2 as jachin__link__pb2
except ImportError:
    # 回退到相对导入（用于直接运行）
    import jachin_link_pb2 as jachin__link__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jachin_link_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JachinLinkGatewayStub(object):
    """============================================================================
    Jachin Link Gateway Service
    ============================================================================
    ========== 基础设施协议（连接、心跳、配对）==========
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/jachin.link.JachinLinkGateway/Connect',
                request_serializer=jachin__link__pb2.ConnectRequest.SerializeToString,
                response_deserializer=jachin__link__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/jachin.link.JachinLinkGateway/SendHeartbeat',
                request_serializer=jachin__link__pb2.Heartbeat.SerializeToString,
                response_deserializer=jachin__link__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Pair = channel.unary_unary(
                '/jachin.link.JachinLinkGateway/Pair',
                request_serializer=jachin__link__pb2.PairingRequest.SerializeToString,
                response_deserializer=jachin__link__pb2.PairingResponse.FromString,
                _registered_method=True)
        self.InvokePlugin = channel.unary_unary(
                '/jachin.link.JachinLinkGateway/InvokePlugin',
                request_serializer=jachin__link__pb2.PluginRequest.SerializeToString,
                response_deserializer=jachin__link__pb2.PluginResponse.FromString,
                _registered_method=True)
        self.StreamPlugin = channel.unary_stream(
                '/jachin.link.JachinLinkGateway/StreamPlugin',
                request_serializer=jachin__link__pb2.PluginRequest.SerializeToString,
                response_deserializer=jachin__link__pb2.PluginResponse.FromString,
                _registered_method=True)
        self.ExecuteCommandRequest = channel.unary_unary(
                '/jachin.link.JachinLinkGateway/ExecuteCommandRequest',
                request_serializer=jachin__link__pb2.ExecuteCommand.SerializeToString,
                response_deserializer=jachin__link__pb2.ExecuteCommandResponse.FromString,
                _registered_method=True)
        self.ProcessAI = channel.unary_unary(
                '/jachin.link.JachinLinkGateway/ProcessAI',
                request_serializer=jachin__link__pb2.AIRequest.SerializeToString,
                response_deserializer=jachin__link__pb2.AIResponse.FromString,
                _registered_method=True)
        self.StreamAI = channel.unary_stream(
                '/jachin.link.JachinLinkGateway/StreamAI',
                request_serializer=jachin__link__pb2.AIRequest.SerializeToString,
                response_deserializer=jachin__link__pb2.AIResponse.FromString,
                _registered_method=True)


class JachinLinkGatewayServicer(object):
    """============================================================================
    Jachin Link Gateway Service
    ============================================================================
    ========== 基础设施协议（连接、心跳、配对）==========
    """

    def Connect(self, request, context):
        """连接（首次建立连接）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """心跳检测
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pair(self, request, context):
        """配对（仅首次连接）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokePlugin(self, request, context):
        """========== 通用插件调用协议（Envelope Pattern）==========

        调用插件（通用接口，支持所有插件）
        这是核心接口：无论插件如何扩展，这个接口永远不变
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPlugin(self, request, context):
        """流式调用插件（用于实时对话、流式输出）
        例如：插件返回股票价格实时更新、AI 对话流式输出
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommandRequest(self, request, context):
        """========== 兼容旧版本协议（已废弃，建议迁移到 InvokePlugin）==========

        执行命令（已废弃：请使用 InvokePlugin）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessAI(self, request, context):
        """AI 指令处理（已废弃：请使用 InvokePlugin）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAI(self, request, context):
        """流式 AI 响应（已废弃：请使用 StreamPlugin）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JachinLinkGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=jachin__link__pb2.ConnectRequest.FromString,
                    response_serializer=jachin__link__pb2.ConnectResponse.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=jachin__link__pb2.Heartbeat.FromString,
                    response_serializer=jachin__link__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Pair': grpc.unary_unary_rpc_method_handler(
                    servicer.Pair,
                    request_deserializer=jachin__link__pb2.PairingRequest.FromString,
                    response_serializer=jachin__link__pb2.PairingResponse.SerializeToString,
            ),
            'InvokePlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokePlugin,
                    request_deserializer=jachin__link__pb2.PluginRequest.FromString,
                    response_serializer=jachin__link__pb2.PluginResponse.SerializeToString,
            ),
            'StreamPlugin': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPlugin,
                    request_deserializer=jachin__link__pb2.PluginRequest.FromString,
                    response_serializer=jachin__link__pb2.PluginResponse.SerializeToString,
            ),
            'ExecuteCommandRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommandRequest,
                    request_deserializer=jachin__link__pb2.ExecuteCommand.FromString,
                    response_serializer=jachin__link__pb2.ExecuteCommandResponse.SerializeToString,
            ),
            'ProcessAI': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessAI,
                    request_deserializer=jachin__link__pb2.AIRequest.FromString,
                    response_serializer=jachin__link__pb2.AIResponse.SerializeToString,
            ),
            'StreamAI': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAI,
                    request_deserializer=jachin__link__pb2.AIRequest.FromString,
                    response_serializer=jachin__link__pb2.AIResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jachin.link.JachinLinkGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jachin.link.JachinLinkGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JachinLinkGateway(object):
    """============================================================================
    Jachin Link Gateway Service
    ============================================================================
    ========== 基础设施协议（连接、心跳、配对）==========
    """

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jachin.link.JachinLinkGateway/Connect',
            jachin__link__pb2.ConnectRequest.SerializeToString,
            jachin__link__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jachin.link.JachinLinkGateway/SendHeartbeat',
            jachin__link__pb2.Heartbeat.SerializeToString,
            jachin__link__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pair(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jachin.link.JachinLinkGateway/Pair',
            jachin__link__pb2.PairingRequest.SerializeToString,
            jachin__link__pb2.PairingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokePlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jachin.link.JachinLinkGateway/InvokePlugin',
            jachin__link__pb2.PluginRequest.SerializeToString,
            jachin__link__pb2.PluginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jachin.link.JachinLinkGateway/StreamPlugin',
            jachin__link__pb2.PluginRequest.SerializeToString,
            jachin__link__pb2.PluginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommandRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jachin.link.JachinLinkGateway/ExecuteCommandRequest',
            jachin__link__pb2.ExecuteCommand.SerializeToString,
            jachin__link__pb2.ExecuteCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessAI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jachin.link.JachinLinkGateway/ProcessAI',
            jachin__link__pb2.AIRequest.SerializeToString,
            jachin__link__pb2.AIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jachin.link.JachinLinkGateway/StreamAI',
            jachin__link__pb2.AIRequest.SerializeToString,
            jachin__link__pb2.AIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
