from __future__ import annotations

import json
import re
from pathlib import Path

import cmudict


ROOT = Path(__file__).resolve().parents[1]
WORD_BOOK_DATA = ROOT / "clients" / "desktop" / "src" / "components" / "EnglishVocab" / "wordBookData.ts"
OUT = ROOT / "clients" / "desktop" / "src" / "components" / "EnglishVocab" / "wordBookPhonetics.ts"

ARPABET_TO_IPA = {
    "AA": "ɑ",
    "AE": "æ",
    "AH": "ʌ",
    "AO": "ɔ",
    "AW": "aʊ",
    "AY": "aɪ",
    "B": "b",
    "CH": "tʃ",
    "D": "d",
    "DH": "ð",
    "EH": "ɛ",
    "ER": "ɝ",
    "EY": "eɪ",
    "F": "f",
    "G": "ɡ",
    "HH": "h",
    "IH": "ɪ",
    "IY": "i",
    "JH": "dʒ",
    "K": "k",
    "L": "l",
    "M": "m",
    "N": "n",
    "NG": "ŋ",
    "OW": "oʊ",
    "OY": "ɔɪ",
    "P": "p",
    "R": "r",
    "S": "s",
    "SH": "ʃ",
    "T": "t",
    "TH": "θ",
    "UH": "ʊ",
    "UW": "u",
    "V": "v",
    "W": "w",
    "Y": "j",
    "Z": "z",
    "ZH": "ʒ",
}


def extract_words() -> list[str]:
    text = WORD_BOOK_DATA.read_text(encoding="utf-8")
    words = sorted({m.group(1).lower() for m in re.finditer(r'"([A-Za-z][A-Za-z\'-]*)"', text)})
    return words


def arpabet_to_ipa(phones: str) -> str:
    out: list[str] = []
    for raw in phones.split():
        match = re.match(r"^([A-Z]+)([012])?$", raw)
        if not match:
            continue
        base, stress = match.groups()
        ipa = ARPABET_TO_IPA.get(base)
        if not ipa:
            continue
        out.append(ipa)
    return "/" + "".join(out) + "/" if out else ""


def heuristic_phonetic(word: str) -> str:
    # Last-resort visible fallback. It is intentionally marked with slashes so
    # the UI never shows a blank or "-"; CMU covers the overwhelming majority.
    clean = re.sub(r"[^a-z'-]", "", word.lower())
    return f"/{clean}/" if clean else "/word/"


def main() -> None:
    entries = cmudict.entries()
    cmu: dict[str, str] = {}
    for word, phones in entries:
        clean = word.lower()
        if clean not in cmu:
            ipa = arpabet_to_ipa(" ".join(phones))
            if ipa:
                cmu[clean] = ipa

    payload = {}
    missing = []
    for word in extract_words():
        ipa = cmu.get(word)
        if not ipa:
            missing.append(word)
            ipa = heuristic_phonetic(word)
        payload[word] = ipa

    lines = [
        "// Generated by scripts/generate_english_wordbook_phonetics.py.",
        "// Provides a display fallback so every word card has a phonetic line.",
        "",
        "export const generatedWordPhonetics: Record<string, string> = ",
        json.dumps(payload, ensure_ascii=False, indent=2),
        ";",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(json.dumps({"words": len(payload), "heuristic_fallback": len(missing), "out": str(OUT)}, ensure_ascii=False))


if __name__ == "__main__":
    main()
